<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
		<?= $this->headTitle('ZF Skeleton Application')->setSeparator(' - ')->setAutoEscape(false) ?>

		<?=
				$this->headMeta()
				->appendName('viewport', 'width=device-width, initial-scale=1.0')
				->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?>

        <!-- Le styles -->
		<?=
				$this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
				->prependStylesheet($this->basePath('css/style.css'))
				->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
				->prependStylesheet($this->basePath('css/bootstrap.min.css'))
				->prependStylesheet($this->basePath('css/foundation.css'))
				->prependStylesheet($this->basePath('css/font-awesome.css'))
		?>

        <!-- Scripts -->
		<?=
				$this->headScript()
				->prependFile($this->basePath('js/bootstrap.min.js'))
				->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
		?>
    </head>
    <body>
		<div class="logo"><img src="<?= $this->basePath('img/logo.png') ?>" alt="Logo"></div>
		<ul class="menu">
			<li><a href="#">Home</a></li>
			<li><a href="#">About</a></li>
			<li><a href="#">Team</a></li>
			<li><a href="#">Portfolio</a></li>
			<li><a href="#">Other</a></li>
			<li><a href="#">Contact</a></li>
		</ul>
        
        <div class="container">
<?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>
<?= $this->inlineScript() ?>
    </body>
</html>
