<!-- CONTENU DE LA PAGE HORS HEADER et MAYBE FOOTER-->



<div class="corps_1">
	<h1>WELCOME TO MOTION </h1> 
	
	<p>A smart & Creative Single Page Template</p>	
	<div class="code-slider">
		<a href="#" class="control_next"><img src="<?= $this->basePath('img/next.png') ?>" alt="Logo"></a>
		<a href="#" class="control_prev"><img src="<?= $this->basePath('img/previous.png') ?>" alt="Logo"></a>
		<div id="slider">

			<ul>
				<li style="background: rgb(235,79,78);"><img src="<?= $this->basePath('img/image-s.png') ?>" alt="Logo"></li>
				<li style="background: rgb(235,79,78);"><img src="<?= $this->basePath('img/image-s.png') ?>" alt="Logo"></li>
				<li style="background: rgb(235,79,78);"><img src="<?= $this->basePath('img/image-s.png') ?>" alt="Logo"></li>
				<li style="background: rgb(235,79,78);"><img src="<?= $this->basePath('img/image-s.png') ?>" alt="Logo"></li>
			</ul>  
		</div>
	</div>
</div>


<div class="arroundPurpose">
	<div class="container">
		<div class="row purpose">
			<h2>Smart & Creative</h2>
			<span>This is why you will use it :)</span>
			<div class="col-lg-4">
				<img src="img/icon1.jpg" alt="test" />
				<h3>Multi purpose</h3>
				<span>Lorem ipsum dolor sit amet, consectetur adipisicing..</span>
			</div>
			<div class="col-lg-4">
				<img src="img/icon2.jpg" alt="test" />
				<h3>Flat UI</h3>
				<span>Lorem ipsum dolor sit amet, consectetur adipisicing..</span>
			</div>
			<div class="col-lg-4">
				<img src="img/icon3.jpg" alt="test" />
				<h3>Creative Design </h3>
				<span>Lorem ipsum dolor sit amet, consectetur adipisicing..</span>
			</div>
		</div>
	</div>
</div>

<div class="arroundTalent">
	<div class="container">
		<div class="row talent">
			<h2>Talented & Experts</h2>
			<span>This is our team :)</span>
			<div class="col-lg-3">
				<div class="fiche">
					<img src="img/people.jpg" alt="test" />
					<span class="name">Mahmoud Baghagho</span>
					<span class="grade">Senir UI Designer</span>
					<a href="#" class="link-twitter"><i class="fa fa-twitter" aria-hidden="true"></i> Follow</a>
				</div>
			</div>
			<div class="col-lg-3">
				<div class="fiche">
					<img src="img/people.jpg" alt="test" />
					<span class="name">Mahmoud Baghagho</span>
					<span class="grade">Senir UI Designer</span>
					<a href="#" class="link-twitter"><i class="fa fa-twitter" aria-hidden="true"></i> Follow</a>
				</div>
			</div>
			<div class="col-lg-3">
				<div class="fiche">
					<img src="img/people.jpg" alt="test" />
					<span class="name">Mahmoud Baghagho</span>
					<span class="grade">Senir UI Designer</span>
					<a href="#" class="link-twitter"><i class="fa fa-twitter" aria-hidden="true"></i> Follow</a>
				</div>
			</div>
			<div class="col-lg-3">
				<div class="fiche">
					<img src="img/people.jpg" alt="test" />
					<span class="name">Mahmoud Baghagho</span>
					<span class="grade">Senir UI Designer</span>
					<a href="#" class="link-twitter"><i class="fa fa-twitter" aria-hidden="true"></i> Follow</a>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="arroundSlider2">
	<div class="container slider-elegant">
		<h2>Elegant & Genuine</h2>
		<span>This is how our works looks like :)</span>

		<div data-slick='{"slidesToShow": 4, "slidesToScroll": 4}' class="slider2">
			<div><img src="img/img-slider2.jpg" alt="test" /><span>SMS Clouds</span></div>
			<div><img src="img/img-slider2.jpg" alt="test" /><span>SMS Clouds</span></div>
			<div><img src="img/img-slider2.jpg" alt="test" /><span>SMS Clouds</span></div>
			<div><img src="img/img2-slider2.jpg" alt="test" /><span>SMS Clouds</span></div>
			<div><img src="img/img2-slider2.jpg" alt="test" /><span>SMS Clouds</span></div>
			<div><img src="img/img2-slider2.jpg" alt="test" /><span>SMS Clouds</span></div>
			<div><img src="img/img-slider2.jpg" alt="test" /><span>SMS Clouds</span></div>
			<div><img src="img/img-slider2.jpg" alt="test" /><span>SMS Clouds</span></div>
			<div><img src="img/img-slider2.jpg" alt="test" /><span>SMS Clouds</span></div>
			<div><img src="img/img2-slider2.jpg" alt="test" /><span>SMS Clouds</span></div>
			<div><img src="img/img2-slider2.jpg" alt="test" /><span>SMS Clouds</span></div>
			<div><img src="img/img2-slider2.jpg" alt="test" /><span>SMS Clouds</span></div>
			<div><img src="img/img-slider2.jpg" alt="test" /><span>SMS Clouds</span></div>
			<div><img src="img/img-slider2.jpg" alt="test" /><span>SMS Clouds</span></div>
			<div><img src="img/img-slider2.jpg" alt="test" /><span>SMS Clouds</span></div>
			<div><img src="img/img2-slider2.jpg" alt="test" /><span>SMS Clouds</span></div>
			<div><img src="img/img2-slider2.jpg" alt="test" /><span>SMS Clouds</span></div>
			<div><img src="img/img2-slider2.jpg" alt="test" /><span>SMS Clouds</span></div>
		</div>
	</div>
	<div class="container categorie">
		<div class="row">
			<div class="col-lg-4">
				<div class="content content1 categorie1">
					<h3>Start Up</h3>
					<span>For beginners</span>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="content content2 categorie2">
					<h3>Standart</h3>
					<span>More than what you have dreamed with</span>
					<span class="bite"></span>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="content content3 categorie3">
					<h3>Professional</h3>
					<span>For smart people</span>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="arroundChoice">
	<div class="container">
		<div class="row choice">
			<div class="col-lg-4">
				<div class="content content1">
					<ul>
						<li>Basic pages</li>
						<li>MySQL Databases</li>
						<li>Bandwith</li>
						<li>Storage space</li>
					</ul>
					<div class="price price1">
						<span><sub class="sub">$</sub><b>15</b>/mo</span>
						<button>Order</button>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="content content2">
					<ul>
						<li>Basic pages</li>
						<li>MySQL Databases</li>
						<li>Bandwith</li>
						<li>Storage space</li>    
					</ul>
					<div class="price price2">
						<span><sub class="sub">$</sub><b>25</b>/mo</span>
						<button>Order</button>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="content content3">
					<ul>
						<li>Basic pages</li>
						<li>MySQL Databases</li>
						<li>Bandwith</li>
						<li>Storage space</li>
					</ul>
					<div class="price price3">
						<span><sub class="sub">$</sub><b>35</b>/mo</span>
						<button>Order</button>
					</div>
				</div>
			</div>
		</div>
		<a href="#">And more available plans for all needs .... Check here</a>
	</div>
</div>

<div class="arroundSlider3">

	<div class="container">
		<div class="slider3">
			<div class="single-item2">
				<div><img src="img/last-tweet.jpg" alt="test" /></div>
				<div><img src="img/last-tweet.jpg" alt="test" /></div>
				<div><img src="img/last-tweet.jpg" alt="test" /></div>
				<div><img src="img/last-tweet.jpg" alt="test" /></div>
			</div>
		</div>
	</div>

</div>





<!--



-->
