<div class="corps_1">
	<h1>WELCOME TO MOTION</h1>
	<p>A smart & Creative Single Page Template</p>	
	<div class="code-slider">
		<a href="#" class="control_next"><img src="<?= $this->basePath('img/next.png') ?>" alt="Logo"></a>
		<a href="#" class="control_prev"><img src="<?= $this->basePath('img/previous.png') ?>" alt="Logo"></a>
		<div id="slider">

			<ul>
				<li style="background: rgb(235,79,78);"><img src="<?= $this->basePath('img/image-s.png') ?>" alt="Logo"></li>
				<li style="background: rgb(235,79,78);"><img src="<?= $this->basePath('img/image-s.png') ?>" alt="Logo"></li>
				<li style="background: rgb(235,79,78);"><img src="<?= $this->basePath('img/image-s.png') ?>" alt="Logo"></li>
				<li style="background: rgb(235,79,78);"><img src="<?= $this->basePath('img/image-s.png') ?>" alt="Logo"></li>
			</ul>  
		</div>
	</div>
</div>

<div class="corps_2">
	<h1>smart & Creative</h1>
	<p>A smart & Creative Single Page Template</p>	





</div>